# Generated by Django 5.1.2 on 2024-10-24 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_ec', models.CharField(max_length=255)),
                ('nom_ec', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=255, unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('formation', models.IntegerField(choices=[(1, 'Cours du jour'), (2, 'Cours du soir')])),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.filiere')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.niveau')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc1', models.FloatField(blank=True, null=True)),
                ('cc2', models.FloatField(blank=True, null=True)),
                ('cc3', models.FloatField(blank=True, null=True)),
                ('session_normale', models.FloatField(blank=True, null=True)),
                ('session_avant', models.FloatField(blank=True, null=True)),
                ('ec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.ec')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='UE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_ue', models.CharField(max_length=255)),
                ('nom_ue', models.CharField(max_length=255)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.filiere')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.niveau')),
            ],
        ),
        migrations.AddField(
            model_name='ec',
            name='ue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.ue'),
        ),
    ]
